import React from "react";
import Herosection from "../components/Herosection";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const about = () => {
  return <Herosection title={"OUR STORY"} />;
};

export default about;
